### ISSUE TITLE
Can't get this web interface to work with FireFox

### ISSUE THREAD

**Issue by geebotron** [livepeer/file-video#14]
I have managed to upload a vid - but only using the Chrome browser.

FireFox hangs forever at the "finishing up" stage. I have never managed to get beyond this in Firefox.
It never returns with a URL for the video file.

(It will intermittently hang like this in Chrome too)

The video clips I was testing with were all in the MP4 format, and under 15MB.

Cheers.

**Comment by adamsoffer** [comment]
@rajdeepbharati any idea?

**Comment by geebotron** [comment]
OK - Just had success with FireFox.
The vid was only 6.5MB in size and it took 2-3 mins to return with the URL ...

**Comment by adamsoffer** [comment]
Okay thanks for reporting @geebotron. I've created a [new issue](https://github.com/livepeer/file-video/issues/14) to address the video upload times.
