### ISSUE TITLE
Question: Back-end CIDs for uploaded content

### ISSUE THREAD

**Issue by geebotron** [livepeer/file-video#16]
I believe the onrender back-end to file.video stores the uploaded video content in IPFS.
Is it possible to retrieve the CIDs of the uploaded data objects should one want to "pin" the content oneself, to improve resilience and availability?

If so, how?

**Comment by rajdeepbharati** [comment]
Yes! Suppose you have a video: https://file.video/v/4cd8b731-6424-4985-904c-62dc4abc6b08
You can use this `asset_id` in the [demux get asset endpoint](https://github.com/buidl-labs/Demux#get-assetasset_id) by going to https://demux.onrender.com/asset/4cd8b731-6424-4985-904c-62dc4abc6b08
In the `stream_url` ("stream_url": "https://demuxipfsrevproxy.onrender.com/ipfs/bafybeig3jqhhy2hcsnghrgvivm5q3rwn66fhtt6bganvd7lpbu7obehjfa/root.m3u8") you can find the CID: `bafybeig3jqhhy2hcsnghrgvivm5q3rwn66fhtt6bganvd7lpbu7obehjfa`

The videos are currently pinned on an ipfs node for quick access, and you can pin it to your ipfs node improve resilience.

**Comment by geebotron** [comment]
Excellent! Thanks for the information.
