### ISSUE TITLE
Programatically upload and embeddable player ?

### ISSUE THREAD

**Issue by daslicht** [livepeer/file-video#21]
Hi,
is there a way to programatically upload new videos ?
How about a embedable player or a way to build a custom player?
API to get a video ?
Cheers Marc

https://demux.onrender.com/
shows : This service has been suspended by its owner.

**Comment by rajdeepbharati** [comment]
Hi @daslicht 
> is there a way to programatically upload new videos ?

The backend service is open source and you are free to fork it and make changes: https://github.com/buidl-labs/Demux
You can see it's working in the diagram shown in the readme.
You are also free to use a custom player by forking this (file-video) frontend repo.

> https://demux.onrender.com/

The service has been restarted and is working now
