### ISSUE TITLE
Browser console 405 response on file.video "Finishing up..."

### ISSUE THREAD

**Issue by 1337cookie** [livepeer/file-video#30]
Website gets stuck on "Finishing up..." in chrome with the following in the console. 
```
Failed to load resource: the server responded with a status of 405 ()
```
```
index.js:1 GET https://demux.onrender.com/fileupload/498b2cca-d0b9-4af5-87fa-4c17c52805f0?resumableChunkNumber=18&resumableChunkSize=1048576&resumableCurrentChunkSize=1646301&resumableTotalSize=19472093&resumableType=video%2Fmp4&resumableIdentifier=19472093-flyingmp4&resumableFilename=flying.mp4&resumableRelativePath=flying.mp4&resumableTotalChunks=18 405
```

**Comment by rajdeepbharati** [comment]
Hey @1337cookie, this issue is due to some mishandling of file uploading logs (however, the video works fine). If you wait for a while, the process would complete and would show you a success or failure status in the GUI itself.

**Comment by 1337cookie** [comment]
I did leave the page open for maybe 30 minutes before creating this issue. Working fine now ¯\_(ツ)_/¯
